openapi: 3.0.3
info:
  x-summary: 'Piattaforma Notifiche: API per il Front End del BackOffice'
  title: 'Gestione Aggregati'
  version: '1.0.0'
tags:
  - name: Aggregate
    description: >-
      Invocazioni utilizzabili dai mittenti per la gestione degli aggregati
paths:
  "/aggregate":
    get:
      summary: Ricerca aggregati
      description: >-
        servizio di consultazione della lista degli aggregati
      tags:
        - Aggregate
      operationId: getAggregatesList
      parameters:                
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: lastEvaluatedId
          in: query
          required: false
          schema:
            type: string
        - name: lastEvaluatedName
          in: query
          required: false
          schema:
            type: string

      responses:
        '200':
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AggregatesListResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  "/aggregate/{id}":
    get:
      summary: Dettaglio Aggregato
      description: >-
        servizio per il dettaglio dell'Aggregato
      tags:
        - Aggregate
      operationId: getAggregate
      parameters:
        - $ref: '#/components/parameters/pathAggregate'
      responses:
        '200':
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AggregateResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      summary: Rimozione aggregato
      description: >-
        servizio di rimozione dell'aggregato
      tags:
        - Aggregate
      operationId: deleteApiKeys
      parameters:
        - $ref: '#/components/parameters/pathAggregate'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  
  "/aggregate/{id}/add-pa":
    post:
      summary: Associazione PA - Aggregato
      description: >-
        servizio che associa una lista di PA a un determinato aggregato
      tags:
        - Aggregate
      operationId: addPaListToAggregate
      parameters:
        - $ref: '#/components/parameters/pathAggregate'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPaListRequest"
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
                
  "/aggregate/{id}/associable-pa":
    get:
      summary: Lista PA associabili
      description: >-
        servizio che restituisce la lista della PA associabili all'aggregato
      tags:
        - Aggregate
      operationId: getAssociablePa
      parameters:
        - $ref: '#/components/parameters/pathAggregate'
      responses:
        '200':
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AssociablePaResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  "/usage-plan/template":
    get:
      summary: Lista usagePlan template
      description: >-
        servizio che restituisce la lista dei template per gli usage plan
      tags:
        - UsagePlan
      operationId: getUsagePlanTemplate
      responses:
        '200':
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UsagePlanTemplateResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  parameters:
    pathAggregate:
      description: >-
        Identificativo univoco dell'aggregato
      name: id
      in: path
      required: true
      schema:
        type: string
  
  schemas:
    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    AssociablePaResponse:
      type: array
      items:
        $ref: '#/components/schemas/PaDetail'
    AddPaListRequest:
      title: Lista Pa da Associare
      description: >-
        Dto contenente la lista delle Pa da associare all'aggregato selezionato
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PaDetail'
    AggregatesListResponse:
      title: Elenco Aggregati
      description: >-
        Dto contenente la lista degli aggregati eventualmente paginata e filtrata
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AggregateRow'
        lastEvaluatedId:
          type: string
        lastEvaluatedName:
          type: string
    AggregateRow:
      type: object
      properties:
        id:
          type: string
          description: Id dell'api key
        name:
          type: string
          description: Nome dell'api key
        usagePlanTemplate:
          type: string
          description: template dello usage plan al quale è collegato
        createdAt:
          type: string
          description: Data creazione
          format: date-time
        lastUpdate:
          type: string
          description: Data ultima modifica
          format: date-time
    AggregateResponse:
      title: Dettaglio aggregato
      properties:
        id:
          type: string
          description: Id dell'api key
        name:
          type: string
          description: Nome dell'api key
        usagePlanTemplate:
          type: string
          description: template dello usage plan al quale è collegato
        usagePlanInstance:
          $ref: '#/components/schemas/UsagePlanDetail'
        createdAt:
          type: string
          description: Data creazione
          format: date-time
        lastUpdate:
          type: string
          description: Data ultima modifica
          format: date-time
        associatedPa:
          type: integer
          description: numero di PA associate
        associatedPaList:
          type: array
          items:
            $ref: '#/components/schemas/PaDetail'
    UsagePlanDetail:
      type: object
      properties:
        usagePlanId:
          type: string
          description: id dell'istanza di usagePlan collegata all'aggregato
        usagePlanQuota:
          type: number
        usagePlanRate:
          type: number
        usagePlanBurst:
          type: integer
    PaDetail:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    UsagePlanTemplateResponse:
      title: elenco usagePlan template
      description: >-
        Dto contenente la lista dei template per gli usagePlan
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/UsagePlanTemplate'
    UsagePlanTemplate:
      type: object
      properties:
        id:
          type: string
        name: 
          type: string
        quota:
          type: number
        rate:
          type: number
        burst:
          type: integer
    


